import {publicPath as _publicPath, publicURL as _publicURL, publicDataPath as _publicDataPath} from "../../public-paths.mjs";
// API snapshots are data. These helpers preserve successful text across incremental imports.
export function recordKey(r){const kind=r.kind||r.platform||r.sourceKind;const id=r.id||r.threadId||r.thread_id;if(!['codex','chatgpt'].includes(kind)||typeof id!=='string'||!id)return null;return kind+':'+id}
export function failedRead(r){return r?.success===false||r?.ok===false||r?.contentAvailable===false||r?.error!=null||/^(?:failed|failure|error|denied|not[_-]?found|unavailable|forbidden|timeout|read-failed|rpc-error)$/i.test(String(r?.readStatus||r?.status||r?.outcome||''))}
export function apiState(r){const turns=Array.isArray(r?.turns)?r.turns:[];const messages=turns.flatMap(t=>Array.isArray(t.messages)?t.messages:[]).filter(m=>['user','assistant'].includes(m.role));const nonempty=messages.filter(m=>typeof m.text==='string'&&m.text.trim()).length;
 const failed=failedRead(r);const verified=!failed&&(nonempty>0||r?.success===true||r?.ok===true||r?.readStatus==='success'||['available','available-empty','available-partial'].includes(r?.contentState)||(r?.paginationComplete===true&&Number(r?.pageCount)>0));
 const latestPagination=r?.latestSuccessfulRead?.paginationComplete??r?.paginationComplete;
 const state=failed?'read-failed':!verified?'metadata-only':nonempty===0?'available-empty':latestPagination===true?'available':'available-partial';
 return {state,available:verified,turnCount:turns.length,messageCount:messages.length,nonemptyMessages:nonempty,paginationComplete:r?.paginationComplete===true,latestPaginationComplete:latestPagination===true,reason:failed?(r.reason||r.error?.message||r.error||r.readBoundary||'API read failed'):!verified?'No successful API body read established':nonempty===0?'API read succeeded; returned user/assistant visible text is empty':null};}
function chooseText(oldText,newText){return typeof newText==='string'&&(!oldText||newText.length>=String(oldText).length)?newText:oldText}
function mergeMessages(old=[],incoming=[]){const result=old.map(m=>({...m}));const keys=new Map(result.map((m,i)=>[m.id?m.role+':'+m.id:JSON.stringify([m.role,m.text]),i]));for(const m of incoming){const key=m.id?m.role+':'+m.id:JSON.stringify([m.role,m.text]);const i=keys.get(key);if(i===undefined){keys.set(key,result.length);result.push({...m})}else result[i]={...result[i],...m,text:chooseText(result[i].text,m.text)}}return result}
function mergeTurns(old=[],incoming=[]){const result=old.map(t=>({...t,messages:(t.messages||[]).map(m=>({...m}))}));const keys=new Map(result.map((t,i)=>[t.id||JSON.stringify([t.startedAt,t.completedAt,t.status]),i]));for(const t of incoming){const key=t.id||JSON.stringify([t.startedAt,t.completedAt,t.status]);const i=keys.get(key);if(i===undefined){keys.set(key,result.length);result.push({...t,messages:(t.messages||[]).map(m=>({...m}))})}else {const prior=result[i];result[i]={...prior,...t,messages:mergeMessages(prior.messages,t.messages)};for(const name of ['summary','text','finalText'])if(prior[name]||t[name])result[i][name]=chooseText(prior[name],t[name]);}}
 return result.sort((a,b)=>Number(a.startedAt||0)-Number(b.startedAt||0));}
function uniqueRows(rows){const seen=new Set();return rows.filter(r=>{const k=JSON.stringify(r);if(seen.has(k))return false;seen.add(k);return true})}
function evidence(r,capturedOn){return {capturedOn,source:r.source,readStatus:apiState(r).state,paginationComplete:r.paginationComplete,pageCount:r.pageCount,readBoundary:r.readBoundary}}
export function validateRemotePackage(source){if(!source||typeof source!=='object'||(!Array.isArray(source.records)&&!Array.isArray(source.attempts)&&!Array.isArray(source.readFailures)))throw Error('Expected records[], attempts[] or readFailures[] API package');for(const r of source.records||[]){if(!recordKey(r)||(!Array.isArray(r.turns)&&!failedRead(r)))throw Error('Invalid remote record ID/kind/turns');for(const t of r.turns||[]){if(!Array.isArray(t.messages)||t.messages.some(m=>!m||!['user','assistant'].includes(m.role)||typeof m.text!=='string'))throw Error('Invalid remote visible message schema');}}for(const name of ['attempts','readFailures'])if(source[name]!==undefined&&!Array.isArray(source[name]))throw Error('Invalid '+name+' array');}
export function mergeRemotePackages(prior={},incoming={}){validateRemotePackage(incoming);const scopes=[...new Set([...(prior.scopes?.length?prior.scopes:[prior.scope]),...(incoming.scopes?.length?incoming.scopes:[incoming.scope])].filter(Boolean))];const records=new Map((prior.records||[]).map(r=>[recordKey(r),r]).filter(([k])=>k));const retained=[],added=[],updated=[],rejected=[];const extraAttempts=[];
 for(const original of incoming.records||[]){const r={...original,turns:original.turns||[]};const key=recordKey(r);const old=records.get(key);const nextState=apiState(r);if(old&&apiState(old).available&&!nextState.available){retained.push(key);extraAttempts.push({...evidence(r,incoming.capturedOn),id:r.id,kind:r.kind,error:r.error,reason:nextState.reason,status:nextState.state});continue}
 if(old&&apiState(old).nonemptyMessages>0&&nextState.state==='available-empty'){retained.push(key);extraAttempts.push({...evidence(r,incoming.capturedOn),id:r.id,kind:r.kind,status:'success-empty-response-retained-prior-text'});continue}
 if(!old){records.set(key,{...r,readEvidence:[evidence(r,incoming.capturedOn)],...(nextState.available?{latestSuccessfulRead:evidence(r,incoming.capturedOn)}:{})});added.push(key);continue}
 if(!nextState.available&&!apiState(old).available){records.set(key,{...old,...r});updated.push(key);continue}
 const readEvidence=uniqueRows([...(old.readEvidence||[evidence(old,prior.capturedOn)]),evidence(r,incoming.capturedOn)]);const merged={...old,...r,turns:mergeTurns(old.turns,r.turns),paginationComplete:old.paginationComplete===true||r.paginationComplete===true,readEvidence,latestSuccessfulRead:evidence(r,incoming.capturedOn),readStatus:'success',success:true,ok:true,contentAvailable:true};delete merged.error;delete merged.reason;records.set(key,merged);updated.push(key);}
 const attempts=uniqueRows([...(prior.attempts||[]),...(incoming.attempts||[]),...extraAttempts]);const readFailures=uniqueRows([...(prior.readFailures||[]),...(incoming.readFailures||[]),...extraAttempts.filter(failedRead)]);
 return {package:{...prior,...incoming,schemaVersion:2,scope:scopes.join("; "),scopes,records:[...records.values()],attempts,readFailures,importHistory:[...(prior.importHistory||[]),{capturedOn:incoming.capturedOn,scope:incoming.scope,records:incoming.records?.length||0,attempts:incoming.attempts?.length||0,readFailures:incoming.readFailures?.length||0}]},merge:{added,updated,retained,records:records.size,attempts:attempts.length,readFailures:readFailures.length}};}
export function remoteAttemptGroups(source){const result=new Map();for(const row of [...(source.attempts||[]),...(source.readFailures||[])]){const key=recordKey(row);if(!key)continue;const rows=result.get(key)||[];if(!rows.some(r=>JSON.stringify(r)===JSON.stringify(row)))rows.push(row);result.set(key,rows);}for(const rows of result.values())rows.sort((a,b)=>(Date.parse(a.attemptedAt||a.capturedAt||a.checkedAt||a.at||'')||0)-(Date.parse(b.attemptedAt||b.capturedAt||b.checkedAt||b.at||'')||0));return result}
