import {publicPath as _publicPath, publicURL as _publicURL, publicDataPath as _publicDataPath} from "../../public-paths.mjs";
import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {apiState,mergeRemotePackages,remoteAttemptGroups,validateRemotePackage} from './api-records.mjs';

const DIR=path.dirname(fileURLToPath(import.meta.url));
const HOME=process.env.AI_USER_HOME || _publicPath("$data/user");
const ROOTS=[['codex',_publicPath("$codex/sessions")],['codex',_publicPath("$data/integrations/archived_sessions")],['claude',`${HOME}/.claude/projects`],['pi',`${HOME}/.pi/agent/sessions`],['gemini',`${HOME}/.gemini/tmp`]];
const INDEX=_publicDataPath("本地统一/对话记录/index.json");
const SNAPSHOT=_publicDataPath("本地统一/对话记录/desktop-snapshot.json");
const REMOTE=_publicDataPath("本地统一/对话记录/remote-records.json");
const CATALOG=_publicPath("$codex/sqlite/codex-dev.db");
const DB=_publicPath("$codex/state_5.sqlite");
const HISTORY=_publicPath("$codex/thread_history_1.sqlite");
const PARSER_VERSION=3;
const norm=s=>String(s||'').replaceAll('\\','/').replace(/^\/\/\?\//,'').toLowerCase();
const digest=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,20);
const readJSON=(f, fallback={})=>{try{return JSON.parse(fs.readFileSync(f,'utf8').replace(/^\uFEFF/,''))}catch{return fallback}};
function deepRedact(o,key=''){if(/^(?:email|phone|api[_-]?key|access[_-]?token|refresh[_-]?token|password|secret|authorization|cookie|creator_user_id|creator_account_id)$/i.test(key))return '[REDACTED]';if(typeof o==='string')return key==='hostId'&&o.startsWith('chatgpt:')?'chatgpt-account':redact(o);if(Array.isArray(o))return o.map(v=>deepRedact(v));if(o&&typeof o==='object')return Object.fromEntries(Object.entries(o).map(([k,v])=>[k,deepRedact(v,k)]));return o}
function atomic(f,o){fs.mkdirSync(path.dirname(f),{recursive:true});const tmp=f+'.'+process.pid+'.tmp';fs.writeFileSync(tmp,JSON.stringify(o,null,2),'utf8');fs.renameSync(tmp,f)}
export function redact(s){return String(s??'')
 .replace(/((?:authorization|cookie|set-cookie)\s*[:=]\s*)[^\r\n]+/gi,'$1[REDACTED]')
 .replace(/-----BEGIN [^-]*(?:PRIVATE KEY|OPENSSH)[^-]*-----[\s\S]*?-----END [^-]+-----/g,'[REDACTED PRIVATE KEY]')
 .replace(/\b(?:sk-(?:proj-|ant-)?[A-Za-z0-9_-]{16,}|AIza[\w-]{25,}|gh[pousr]_[\w]{20,}|github_pat_[\w]{20,}|ya29\.[\w.-]{20,})/g,'[REDACTED TOKEN]')
 .replace(/\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]+/g,'[REDACTED JWT]')
 .replace(/((?:["']?)(?:api[_-]?key|access[_-]?token|refresh[_-]?token|id[_-]?token|client[_-]?secret|password|passwd|secret|authorization|cookie|set-cookie)(?:["']?)\s*[:=]\s*)(?:"[^"\r\n]*"|'[^'\r\n]*'|[^\s,}\r\n]+)/gi,'$1[REDACTED]')
 .replace(/\bBearer\s+[\w.+/=-]+/gi,'Bearer [REDACTED]')
 .replace(/([?&](?:key|token|secret|password|auth|signature|code)=)[^\s&#"']+/gi,'$1[REDACTED]')
 .replace(/(https?:\/\/)[^\s/@]+:[^\s/@]+@/gi,'$1[REDACTED]@')
 .replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,'[REDACTED EMAIL]')
 .replace(/(?<!\d)(?:\+?86[ -]?)?1[3-9]\d{9}(?!\d)/g,'[REDACTED PHONE]');}
function walk(root,depth=0,out=[]){if(!fs.existsSync(root))return out;if(depth>14)throw Error('Source directory exceeds bounded depth: '+root);for(const e of fs.readdirSync(root,{withFileTypes:true})){if(e.isSymbolicLink())continue;const f=path.join(root,e.name);if(e.isDirectory()){if(!['node_modules','cache','.git'].includes(e.name))walk(f,depth+1,out)}else if(e.isFile()&&e.name.endsWith('.jsonl'))out.push(f)}return out}
async function* objects(file){const input=fs.createReadStream(file,{encoding:'utf8'});const lines=readline.createInterface({input,crlfDelay:Infinity});let line=0;try{for await(const text of lines){line++;if(!text.trim())continue;try{yield {o:JSON.parse(text.replace(/^\uFEFF/,'')),line}}catch{yield {o:null,line}}}}finally{lines.close();input.destroy()}}
function texts(c){if(typeof c==='string')return c;if(!Array.isArray(c))return '';return c.filter(p=>p&&(p.type===undefined||['text','input_text','output_text'].includes(p.type))).map(p=>p.text??'').join('\n')}
function contentKind(m){const s=String(m.text||'').trimStart();if(/^Automation run instructions/i.test(s))return 'automation-instruction';if(/^Message Type:\s*(NEW_TASK|MESSAGE|FINAL_ANSWER)/.test(s))return 'collaboration-envelope';if(/^(?:# AGENTS\.md instructions|<environment_context>|<session_context>|<user_instructions>|<external_[a-z_]+>)/.test(s))return 'context-envelope';return m.role==='assistant'?'assistant-text':'user-role-text';}
function messages(o,platform){if(!o)return [];if(platform==='codex'){const p=o.payload;if(o.type==='response_item'&&p?.type==='message'&&['user','assistant'].includes(p.role))return [{role:p.role,text:texts(p.content),timestamp:o.timestamp}];return []}
 if(platform==='claude'){if(['user','assistant'].includes(o.type)&&o.message&&!o.isMeta)return [{role:o.message.role||o.type,text:texts(o.message.content),timestamp:o.timestamp}];return []}
 if(platform==='pi'){const m=o.message||(o.role?o:null);if(m&&['user','assistant'].includes(m.role))return [{role:m.role,text:texts(m.content||m.parts),timestamp:o.timestamp||o.t}];return []}
 if(platform==='gemini'){const ms=o.$set?.messages||o.messages||[];return ms.filter(m=>['user','gemini','assistant'].includes(m.type||m.role)).map(m=>({role:m.type==='gemini'?'assistant':m.role||m.type,text:texts(m.content),timestamp:m.timestamp}));}return []}
function safePath(f){const n=norm(f);return ROOTS.some(([,r])=>n.startsWith(norm(r)+'/'))}
function sqliteMetadata(){const out=new Map();let issue=null;try{process.env.NODE_NO_WARNINGS='1';}catch{}return import('node:sqlite').then(({DatabaseSync})=>{const d=new DatabaseSync(DB,{readOnly:true});try{for(const o of d.prepare('SELECT id,rollout_path,cwd,title,source,thread_source,agent_path,agent_role,has_user_event,archived,created_at,updated_at,project_id FROM threads').all())out.set(o.id,o)}finally{d.close()}return {out,issue}}).catch(e=>({out,issue:String(e.message)}))}
async function historyCounts(){const {DatabaseSync}=await import('node:sqlite');const d=new DatabaseSync(HISTORY,{readOnly:true});try{return new Map(d.prepare("SELECT thread_id, COUNT(*) n FROM thread_items WHERE item_type IN ('userMessage','agentMessage') GROUP BY thread_id").all().map(r=>[r.thread_id,r.n]))}finally{d.close()}}
async function* visible(r){if(r.path){for await(const {o,line}of objects(r.path)){for(const m of messages(o,r.platform))yield {m,line}}return}if(r.historyMessages){const {DatabaseSync}=await import('node:sqlite');const d=new DatabaseSync(HISTORY,{readOnly:true});try{for(const o of d.prepare("SELECT item_json,rollout_ordinal,created_at_ms FROM thread_items WHERE thread_id=? AND item_type IN ('userMessage','agentMessage') ORDER BY rollout_ordinal").iterate(r.nativeId)){const p=JSON.parse(o.item_json);yield {m:{role:p.type==='userMessage'?'user':'assistant',text:p.type==='userMessage'?texts(p.content):p.text||'',timestamp:new Date(o.created_at_ms).toISOString()},line:null,ordinal:o.rollout_ordinal}}}finally{d.close()}return}if(r.apiContentAvailable){const source=readJSON(REMOTE,{records:[]}).records.find(a=>a.id===r.nativeId&&a.kind===r.platform);for(const turn of source?.turns||[])for(const m of turn.messages||[])if(['user','assistant'].includes(m.role))yield {m:{role:m.role,text:m.text,timestamp:turn.startedAt?new Date(turn.startedAt*1000).toISOString():null},line:null,ordinal:null};}}
function bindings(){const m=new Map();for(const host of ['codex','claude']){const dir=_publicPath("$codex/context/bindings/")+host;if(!fs.existsSync(dir))continue;for(const name of fs.readdirSync(dir).filter(n=>n.endsWith('.json'))){const f=path.join(dir,name),o=readJSON(f);m.set(host+':'+name.slice(0,-5),{...o,evidence:f})}}return m}
function classification(row){const cwd=norm(row.cwd),controlled=cwd.match(/^(.*\/work\/(?:behavior|activation-behavior))\/runs\//);if(controlled){const harness=controlled[1]+'/run.mjs';if(fs.existsSync(harness))return {kind:'test',humanCandidate:false,testEvidence:harness,evidence:'controlled behavior/activation-behavior run directory with existing verified harness; UI source does not prove human'};}
 if(/(?:^|[\\/])(?:swarm|subagents|agents)[\\/]/i.test(row.path)||row.recordType==='collaboration-event-log'||row.parentId||row.agentPath||(row.source&&typeof row.source==='object')||/subagent/i.test(String(row.source)))return {kind:'internal-agent',evidence:'parent/source/agent_path or dedicated agent/collaboration-log path'};
 if(/(?:^|[\\/_-])(?:smoke|test|validation|fixture)(?:[\\/_-]|$)/i.test(row.path+' '+row.cwd))return {kind:'test',evidence:'explicit test/smoke/validation path marker'};
 if(row.platform==='codex'&&['vscode','desktop'].includes(row.source)&&row.userMessages>0)return {kind:'human',evidence:'root native UI session + user message; provisional human candidate, not identity proof',humanCandidate:true};
 if(row.platform==='claude'&&row.userType==='external'&&row.userMessages>0)return {kind:'human',evidence:'root userType external; automation may also use external role'};
 return {kind:'unknown',evidence:'human versus automation not established; user role alone is insufficient'};}
function association(row,binding){if(binding?.project){let branch=binding.branchId||binding.branch||null,branchEvidence=branch?binding.evidence:null;if(!branch&&binding.ledger&&fs.existsSync(binding.ledger)){const body=fs.readFileSync(binding.ledger,'utf8').slice(0,4096);const candidates=[...new Set([...body.matchAll(/--branch\s+([A-Za-z0-9_-]+)/g)].map(m=>m[1]))];const statePath=path.join(binding.project,'共享状态.md');if(candidates.length===1&&fs.existsSync(statePath)&&fs.readFileSync(statePath,'utf8').includes('branch:'+candidates[0])){branch=candidates[0];branchEvidence=binding.ledger;}}return {project:binding.project,branch,branchEvidence,ledger:binding.ledger||null,evidence:binding.evidence,method:'explicit-session-binding'};}
 if(row.cwd){let dir=path.resolve(row.cwd);for(let i=0;i<12;i++){const pointer=path.join(dir,'项目.md');if(fs.existsSync(pointer)){const first=fs.readFileSync(pointer,'utf8').split(/\r?\n/)[0].replace(/^[#>*\-\s`"']+|[`"'\s]+$/g,'');if(path.isAbsolute(first)&&fs.existsSync(path.join(first,'核心.md')))return {project:first,branch:null,method:'project-pointer',evidence:pointer};}const jsonPointer=path.join(dir,'.project.json');const p=readJSON(jsonPointer,{});const target=p.project||p.projectPath;if(typeof target==='string'&&path.isAbsolute(target)&&fs.existsSync(path.join(target,'核心.md')))return {project:target,branch:null,method:'json-project-pointer',evidence:jsonPointer};if(fs.existsSync(path.join(dir,'核心.md')))return {project:dir,branch:null,method:'cwd-ancestor-project-root',evidence:path.join(dir,'核心.md')};const parent=path.dirname(dir);if(parent===dir)break;dir=parent;}}
 return {project:null,branch:null,method:'unknown',evidence:null};}
export async function parse(file,platform,db=new Map()){const stat=fs.statSync(file);const filenameId=path.basename(file).match(/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i)?.[1];const row={id:platform+':'+digest(norm(file)),nativeId:filenameId||null,platform,path:file,size:stat.size,mtimeMs:stat.mtimeMs,cwd:null,title:null,source:null,parentId:null,createdAt:null,updatedAt:new Date(stat.mtimeMs).toISOString(),messages:0,userMessages:0,parseErrors:0,firstUser:null,parserVersion:PARSER_VERSION};
 for await(const {o,line} of objects(file)){if(!o){row.parseErrors++;continue}if((platform==='codex'&&o.type==='session_meta')||(platform==='pi'&&o.type==='session')){const p=o.payload||o;if(platform!=='codex'||!filenameId||p.id===filenameId){row.nativeId=filenameId||p.id||p.session_id;row.cwd=p.cwd;row.source=p.source;row.parentId=p.parent_thread_id||p.parentSessionId;row.createdAt=p.timestamp||o.timestamp;row.metadataLine=line;}}
 if(platform==='claude'){if(path.basename(file).startsWith('agent-')){row.parentId ||= o.sessionId;row.nativeId=path.basename(file,'.jsonl');row.recordType='agent-transcript'}else row.nativeId ||= o.sessionId;row.cwd ||= o.cwd;row.userType ||= o.userType; if(o.isSidechain)row.parentId ||= 'sidechain';if(o.type==='summary')row.title ||= o.summary;}
 if(platform==='gemini'){row.nativeId ||= o.sessionId;row.createdAt ||= o.startTime;}
 if(platform==='pi'&&o.type==='session_info')row.title=o.name;
 for(const m of messages(o,platform)){if(!m.text)continue;row.messages++;if(m.role==='user'){row.userMessages++;row.firstUser ||= redact(m.text).slice(0,300)}}}
 const native=db.get(row.nativeId);if(native){row.title=native.title;row.updatedAt=new Date(native.updated_at*1000).toISOString();row.updatedAtSource=DB+'#threads/'+native.id+'/updated_at';row.cwd=native.cwd||row.cwd;row.source ||= native.source;row.agentPath=native.agent_path;row.archived=!!native.archived;row.desktopProjectId=native.project_id;row.metadataEvidence=DB+'#threads/'+native.id;}
 row.id=row.nativeId?platform+':'+row.nativeId:row.id; // Wire records lack native ID: keep stable path hash.
 if(platform==='pi'&&path.basename(file).startsWith('collaboration-')){row.recordType='collaboration-event-log';row.id=platform+':collaboration:'+digest(norm(file));}
 row.title=redact(row.title||row.firstUser||path.basename(file)).replace(/\s+/g,' ').slice(0,250);delete row.firstUser;return row;}
function load(){const x=readJSON(INDEX,null);if(!x)throw Error('No index. Run refresh first.');return x}
function summary(rows){const platforms={},kinds={};for(const r of rows){platforms[r.platform]=(platforms[r.platform]||0)+1;kinds[r.kind]=(kinds[r.kind]||0)+1}return {total:rows.length,platforms,kinds,unknownProject:rows.filter(r=>!r.association?.project).length,metadataOnly:rows.filter(r=>!r.path&&!r.historyMessages&&!r.apiContentAvailable).length,rawLog:rows.filter(r=>r.path).length,sqliteProjectionFallback:rows.filter(r=>!r.path&&r.historyMessages).length,remoteAPIFallback:rows.filter(r=>!r.path&&!r.historyMessages&&r.apiContentAvailable).length}}
// Capture the chat that generated a real operation. No background scan, model
// call, or dependency on a later manual full refresh.
export async function refreshThread(nativeId,{indexFile=INDEX}={}){
 if(!/^[0-9a-f-]{36}$/i.test(nativeId||''))throw Error('Original Codex thread ID required');
 const {DatabaseSync}=await import('node:sqlite');
 const db=new DatabaseSync(DB,{readOnly:true});let native;
 try{native=db.prepare('SELECT id,rollout_path,cwd,title,source,thread_source,agent_path,has_user_event,archived,updated_at,project_id FROM threads WHERE id=?').get(nativeId);}finally{db.close();}
 if(!native)return {status:'not-yet-persisted',threadId:nativeId};
 if(native.agent_path||/subagent/i.test(String(native.thread_source))||!['desktop','vscode'].includes(native.source))return {status:'not-root-chat',threadId:nativeId};
 const lock=indexFile+'.lock';let fd;
 try{fd=fs.openSync(lock,'wx');}catch(error){if(error.code==='EEXIST')return {status:'busy-preserve-current-index',threadId:nativeId};throw error;}
 fs.writeFileSync(fd,JSON.stringify({pid:process.pid,startedAt:new Date().toISOString(),threadId:nativeId}));
 try{
  const old=readJSON(indexFile,{schemaVersion:1,items:[],sources:[]});
  const id='codex:'+nativeId,previous=old.items.find(r=>r.id===id);
  let row;
  if(safePath(native.rollout_path)&&fs.existsSync(native.rollout_path))row=await parse(native.rollout_path,'codex',new Map([[nativeId,native]]));
  else{
   let historyMessages=previous?.historyMessages||0;
   if(fs.existsSync(HISTORY)){const history=new DatabaseSync(HISTORY,{readOnly:true});try{historyMessages=history.prepare("SELECT COUNT(*) n FROM thread_items WHERE thread_id=? AND item_type IN ('userMessage','agentMessage')").get(nativeId).n;}finally{history.close();}}
   row={id,nativeId,platform:'codex',path:null,originalPath:native.rollout_path,cwd:native.cwd,title:redact(native.title).slice(0,250),source:native.source,agentPath:native.agent_path,archived:!!native.archived,userMessages:native.has_user_event?1:0,historyMessages,updatedAt:new Date(native.updated_at*1000).toISOString(),metadataEvidence:DB+'#threads/'+nativeId};
  }
  row={...previous,...row};Object.assign(row,classification(row));
  if(fs.existsSync(CATALOG)){const catalog=new DatabaseSync(CATALOG,{readOnly:true});try{const display=catalog.prepare('SELECT display_title FROM local_thread_catalog WHERE thread_id=?').get(nativeId);if(display?.display_title)row.title=redact(display.display_title).slice(0,250);}finally{catalog.close();}}
  const bindingFile=`${HOME}/.codex/context/bindings/codex/${nativeId}.json`,currentBinding=readJSON(bindingFile,null);
  row.association=association(row,currentBinding?{...currentBinding,evidence:bindingFile}:null);
  row.operationCapturedAt=new Date().toISOString();
  const items=old.items.filter(r=>r.id!==id);items.push(row);
  items.sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))||a.id.localeCompare(b.id));
  atomic(indexFile,{...old,items,coverage:summary(items),lastOperationCapture:{threadId:nativeId,at:row.operationCapturedAt,scope:'Only the originating original root chat; full-source scan time remains refreshedAt'}});
  return {status:'captured',threadId:nativeId,added:!previous,contentAvailable:!!(row.path||row.historyMessages||row.apiContentAvailable)};
 }finally{fs.closeSync(fd);fs.unlinkSync(lock);}
}
export async function refresh(){const lock=INDEX+'.lock';let fd;try{fd=fs.openSync(lock,'wx')}catch{const prior=readJSON(lock,null);let alive=true;if(prior?.pid){try{process.kill(prior.pid,0)}catch(e){alive=e.code!=='ESRCH'}}if(prior?.pid&&!alive){fs.unlinkSync(lock);fd=fs.openSync(lock,'wx')}else throw Error('Another refresh is running or lock owner unknown; lock '+lock)}fs.writeFileSync(fd,JSON.stringify({pid:process.pid,startedAt:new Date().toISOString()}));try{const old=readJSON(INDEX,{items:[]});const oldPaths=new Map(old.items.filter(r=>r.path).map(r=>[norm(r.path),r]));const {out:db,issue}=await sqliteMetadata();const bound=bindings();const items=[],sources=[],errors=[];let changed=0,unchanged=0;
 for(const [platform,root]of ROOTS){let files=[];try{files=walk(root);if(platform==='gemini')files=files.filter(f=>norm(f).includes('/chats/'))}catch(e){errors.push({root,error:e.message})}sources.push({platform,root,exists:fs.existsSync(root),files:files.length,scope:platform==='gemini'?'only tmp/*/chats JSONL':'only named session source, no symlinks; max depth 14'});
 for(const file of files){const s=fs.statSync(file),prev=oldPaths.get(norm(file));let row;if(prev&&prev.parserVersion===PARSER_VERSION&&prev.size===s.size&&prev.mtimeMs===s.mtimeMs){row={...prev};unchanged++;const native=db.get(row.nativeId);if(native){row.title=redact(native.title).slice(0,250);row.archived=!!native.archived;row.updatedAt=new Date(native.updated_at*1000).toISOString();row.updatedAtSource=DB+'#threads/'+native.id+'/updated_at';row.cwd=native.cwd||row.cwd;row.agentPath=native.agent_path;}}else{try{row=await parse(file,platform,db);changed++}catch(e){errors.push({file,error:e.message});continue}}Object.assign(row,classification(row));row.association=association(row,bound.get(platform+':'+row.nativeId));items.push(row)}}
 const seen=new Set(items.map(r=>r.id));for(const native of db.values()){const id='codex:'+native.id;if(seen.has(id))continue;const row={id,nativeId:native.id,platform:'codex',path:safePath(native.rollout_path)&&fs.existsSync(native.rollout_path)?native.rollout_path:null,originalPath:native.rollout_path,cwd:native.cwd,title:redact(native.title).slice(0,250),source:native.source,agentPath:native.agent_path,archived:!!native.archived,messages:null,userMessages:native.has_user_event?1:0,metadataEvidence:DB+'#threads/'+native.id,updatedAt:new Date(native.updated_at*1000).toISOString()};Object.assign(row,classification(row));row.association=association(row,bound.get(id));items.push(row);seen.add(id)}
 sources.push({platform:'codex',root:DB,exists:fs.existsSync(DB),conversations:db.size,scope:'read-only threads metadata; preserved even when original path is missing'});
 const sessionIndex=`${HOME}/.codex/session_index.jsonl`;let nameRows=0;if(fs.existsSync(sessionIndex)){for await(const {o}of objects(sessionIndex)){if(!o?.id)continue;nameRows++;const id='codex:'+o.id;let r=items.find(r=>r.id===id);if(!r){r={id,nativeId:o.id,platform:'codex',path:null,title:redact(o.thread_name||o.id),kind:'unknown',evidence:'session_index naming record without source body',association:{project:null,branch:null,method:'unknown',evidence:null},updatedAt:o.updated_at};items.push(r)}r.nameIndexEvidence=sessionIndex;}}sources.push({platform:'codex',root:sessionIndex,exists:fs.existsSync(sessionIndex),records:nameRows,scope:'append naming index, IDs merged; no body implied'});
 const liveDir=`${HOME}/.claude/sessions`;let liveRows=0;if(fs.existsSync(liveDir)){for(const name of fs.readdirSync(liveDir).filter(n=>n.endsWith('.json'))){const f=path.join(liveDir,name),o=readJSON(f);if(!o.sessionId)continue;liveRows++;const id='claude:'+o.sessionId;let r=items.find(r=>r.id===id);if(!r){r={id,nativeId:o.sessionId,platform:'claude',path:null,cwd:o.cwd||null,title:redact(o.name||o.sessionId),kind:'unknown',evidence:'live session descriptor, no original transcript found',association:{project:null,branch:null,method:'unknown',evidence:null}};r.association=association(r,bound.get(id));items.push(r)}r.liveSessionEvidence=f;r.liveStatus=o.status;}}sources.push({platform:'claude',root:liveDir,exists:fs.existsSync(liveDir),records:liveRows,scope:'direct JSON live session descriptors; key files/socket paths omitted'});
 const snap=readJSON(SNAPSHOT,{});const apiRows=[...(snap.sidebar?.pinnedThreads||[]),...(snap.sidebar?.threads||[])];for(const v of Object.values(snap)){if(v&&typeof v==='object'&&!Array.isArray(v)&&Array.isArray(v.threads))apiRows.push(...v.threads)}for(const a of apiRows){const platform=a.kind==='chatgpt'?'chatgpt':'codex',id=platform+':'+a.id;const existing=items.find(r=>r.id===id);if(existing){existing.apiEvidence=SNAPSHOT;existing.apiStatus=a.status;continue}const row={id,nativeId:a.id,platform,path:null,cwd:a.cwd||null,title:redact(a.title||a.id),kind:'unknown',evidence:'desktop API metadata; identity not established',association:{project:null,branch:null,method:'unknown',evidence:null},desktopProjectId:a.projectId||null,metadataEvidence:SNAPSHOT,updatedAt:a.updatedAt?new Date(a.updatedAt*1000).toISOString():null};items.push(row)}
 try{const counts=await historyCounts();for(const [id,count]of counts){let r=items.find(r=>r.id==='codex:'+id);if(!r){r={id:'codex:'+id,nativeId:id,platform:'codex',path:null,title:id,kind:'unknown',evidence:'local history projection without native thread metadata',association:{project:null,branch:null,method:'unknown',evidence:null}};items.push(r)}r.historyMessages=count;r.historyEvidence=HISTORY+'#thread_items/'+id;}sources.push({platform:'codex',root:HISTORY,exists:true,conversations:counts.size,scope:'read-only userMessage/agentMessage projection fallback for missing log; tools/reasoning excluded'})}catch(e){errors.push({source:HISTORY,error:e.message})}
 try{const {DatabaseSync}=await import('node:sqlite');const d=new DatabaseSync(CATALOG,{readOnly:true});try{const catalog=d.prepare('SELECT host_id,thread_id,display_title,cwd,source_kind,source_updated_at,project_id FROM local_thread_catalog').all();for(const a of catalog){const platform=/chatgpt/i.test(a.source_kind)?'chatgpt':'codex',id=platform+':'+a.thread_id;let r=items.find(r=>r.id===id);if(!r){r={id,nativeId:a.thread_id,platform,path:null,cwd:a.cwd||null,title:redact(a.display_title),kind:'unknown',evidence:'desktop local catalog metadata',association:{project:null,branch:null,method:'unknown',evidence:null}};r.association=association(r,bound.get(id));items.push(r)}r.catalogEvidence=CATALOG+'#local_thread_catalog/'+a.thread_id;r.hostId=a.host_id.startsWith('chatgpt:')?'chatgpt-account':a.host_id;r.desktopProjectId ||=a.project_id;if(a.display_title)r.title=redact(a.display_title).slice(0,250)}sources.push({platform:'codex-app',root:CATALOG,exists:true,conversations:catalog.length,scope:'read-only local_thread_catalog metadata; not account-wide cloud export'})}finally{d.close()}}catch(e){errors.push({source:CATALOG,error:e.message})}
 const remote=readJSON(REMOTE,{records:[]});for(const a of remote.records||[]){const platform=a.kind==='chatgpt'?'chatgpt':'codex',id=platform+':'+a.id;let r=items.find(r=>r.id===id);if(!r){r={id,nativeId:a.id,platform,path:null,title:redact(a.title||a.id),kind:'unknown',evidence:'desktop remote API record; identity not established',association:{project:null,branch:null,method:'unknown',evidence:null}};items.push(r)}const state=apiState(a);r.apiContentAvailable=state.available;r.apiContentState=state.state;r.apiContentReason=deepRedact(state.reason);r.apiEvidence=REMOTE;r.apiReadBoundary=a.readBoundary;r.apiPaginationComplete=state.paginationComplete;r.apiLatestPaginationComplete=state.latestPaginationComplete;r.apiPageCount=a.pageCount;r.apiReadEvidence=a.readEvidence;r.apiTurnCount=state.turnCount;r.apiMessageCount=state.messageCount;r.apiNonemptyMessages=state.nonemptyMessages;r.hostId=a.hostId?.startsWith('chatgpt:')?'chatgpt-account':a.hostId;}
 for(const [id,attempts]of remoteAttemptGroups(remote)){let r=items.find(r=>r.id===id);if(!r){const [platform,...rest]=id.split(':');r={id,nativeId:rest.join(':'),platform,path:null,title:rest.join(':'),kind:'unknown',evidence:'remote read attempt without successful transcript',association:{project:null,branch:null,method:'unknown',evidence:null}};items.push(r)}r.apiReadAttempts=deepRedact(attempts);r.apiLatestAttempt=deepRedact(attempts.at(-1));r.apiAttemptEvidence=REMOTE;if(!r.apiContentAvailable){r.apiContentState=attempts.some(a=>apiState(a).state==='read-failed')?'read-failed':r.apiContentState||'metadata-only';r.apiContentReason=deepRedact(r.apiLatestAttempt?.reason||r.apiLatestAttempt?.error||r.apiContentReason||'Remote read attempt did not provide a verified body');}}
 if(remote.records?.length||remote.attempts?.length||remote.readFailures?.length)sources.push({platform:'remote-api',root:REMOTE,exists:true,conversations:remote.records?.length||0,attempts:remote.attempts?.length||0,readFailures:remote.readFailures?.length||0,scope:(remote.scopes||[remote.scope]).filter(Boolean).join("; "),scopes:remote.scopes||[remote.scope],scopes:remote.scopes});
 items.sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))||a.id.localeCompare(b.id));const result={schemaVersion:1,refreshedAt:new Date().toISOString(),sources,coverage:summary(items),refresh:{changed,unchanged},errors,sqliteIssue:issue,scope:'All discovered files under explicit local source roots, read-only Codex history/catalog projections, supplied desktop snapshot and API message pages; account-wide cloud history not implied. Running logs stay at original path. Index stores metadata, not full transcripts.',items};atomic(INDEX,result);const navigation=(await import('./management.mjs')).generateNavigation();return {...result,items:undefined,navigation}}finally{if(fd!==undefined)fs.closeSync(fd);fs.unlinkSync(lock)}}
function page(items,args){const offset=integer(args.offset,0,0,1e9),limit=integer(args.limit,20,1,100);return {total:items.length,offset,limit,nextOffset:offset+limit<items.length?offset+limit:null,items:items.slice(offset,offset+limit)}}
function integer(v,d,min,max){if(v===undefined)return d;const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw Error('Invalid numeric pagination value');return n}
function selected(index,args){return index.items.filter(r=>(!args.platform||r.platform===args.platform)&&(!args.kind||r.kind===args.kind)&&(!args.project||norm(r.association?.project).includes(norm(args.project)))&&(!args.branch||r.association?.branch===args.branch))}
export async function read(id,args={}){const index=load();const r=index.items.find(r=>r.id===id)||index.items.find(r=>r.nativeId===id);if(!r)throw Error('Unknown conversation ID');if(!r.path&&!r.historyMessages&&!r.apiContentAvailable)return {conversation:r,contentAvailable:false,contentState:r.apiContentState||'metadata-only',reason:r.apiContentReason||'Metadata only; cloud/API read or missing original log required',apiLatestAttempt:r.apiLatestAttempt||null,items:[],total:0};if(r.path&&!safePath(r.path))throw Error('Source outside allowlisted roots');const offset=integer(args.offset,0,0,1e9),limit=integer(args.limit,10,1,50),chars=integer(args.chars,4000,1,20000),charOffset=integer(args['char-offset'],0,0,1e9);let total=0;const items=[];for await(const {m,line,ordinal}of visible(r)){if(!m.text)continue;const index=total++;if(index<offset||items.length>=limit)continue;const clean=redact(m.text);items.push({index,role:m.role,contentKind:contentKind(m),timestamp:m.timestamp,line,ordinal,characters:clean.length,charOffset,text:clean.slice(charOffset,charOffset+chars),truncated:clean.length>charOffset+chars})}return {conversation:r,contentAvailable:true,contentState:total===0?'available-empty':(!r.path&&!r.historyMessages?r.apiContentState:'available'),apiLayer:r.apiEvidence?{state:r.apiContentState,reason:r.apiContentReason,paginationComplete:r.apiPaginationComplete,latestPaginationComplete:r.apiLatestPaginationComplete,pageCount:r.apiPageCount,latestAttempt:r.apiLatestAttempt}:null,contentSource:r.path||(r.historyMessages?HISTORY:REMOTE),total,offset,limit,nextOffset:offset+limit<total?offset+limit:null,items,policy:'User/assistant visible text only; user role may contain context/automation/collaboration envelopes and is not human authorization. Tools, reasoning, system/developer messages omitted; known credential patterns redacted. SQLite/API fallback is a projection, not proof of complete original log.'}}
export async function search(query,args={}){if(!query||!String(query).trim())throw Error('--query required');const q=String(query).toLocaleLowerCase();const hits=[];for(const r of selected(load(),args)){let match=null;if(redact(r.title).toLocaleLowerCase().includes(q))match={field:'title',text:r.title};if(!match&&((r.path&&safePath(r.path))||r.historyMessages||r.apiContentAvailable)){for await(const {m,line,ordinal}of visible(r)){const clean=redact(m.text),at=clean.toLocaleLowerCase().indexOf(q);if(at>=0){match={field:'message',role:m.role,line,ordinal,text:clean.slice(Math.max(0,at-100),at+query.length+180)};break}}}if(match)hits.push({id:r.id,nativeId:r.nativeId,platform:r.platform,kind:r.kind,title:r.title,path:r.path,association:r.association,match})}return {...page(hits,args),policy:'Literal query against redacted user/assistant visible text and title. Tool output, reasoning and credentials are not searchable; one hit per conversation. Full scan within source allowlist.'}}
const HELP={commands:{refresh:'Incremental metadata refresh; original logs remain in place',list:'--offset N --limit 1..100 --platform codex|claude|pi|gemini|chatgpt --kind human|internal-agent|test|unknown --project TEXT',search:'--query TEXT [same list filters/pagination]',read:'--id ID --offset MESSAGE --limit 1..50 [--chars 1..20000 --char-offset N]',coverage:'Source discovery, counts and boundaries'},output:'JSON UTF-8',index:INDEX,classification:'Evidence-based provisional labels; role user is not proof of human authorship',security:'Only user/assistant visible text; no tools/reasoning/system/developer messages; redact before query and output. Heuristics are not a secret-detection guarantee.'};
HELP.commands.navigation='Generate project > responsibility > chat HTML view from existing index, bindings and current shared-state';
HELP.commands['routing-status']='Current event-driven classification status and pending native application';
HELP.commands.recent='Original native updated_at descending root UI candidates; does not change chat creation/update time';
HELP.commands.resume='--id ID [--chars N]; read current branch goal/criteria and recent actual visible text, no messages sent';
HELP.commands['import-api']='--input ABS_JSON; import already obtained desktop snapshot or remote records; redact, preserve previous snapshot, refresh; does not fetch API';
export async function importAPI(input){if(!input||!path.isAbsolute(input))throw Error('--input must be absolute JSON file');const source=readJSON(input,null);if(!source||typeof source!=='object')throw Error('Invalid API input JSON');let target,clean,merge=null;const isRemote=Array.isArray(source.records)||Array.isArray(source.attempts)||Array.isArray(source.readFailures);if(isRemote){validateRemotePackage(source);target=REMOTE;}else if(source.sidebar&&Array.isArray(source.sidebar.threads)){target=SNAPSHOT;}else throw Error('Expected records[], attempts[], readFailures[] or sidebar.threads[] source');
 const lock=target+'.import.lock';let fd;try{fd=fs.openSync(lock,'wx')}catch{const prior=readJSON(lock,null);let alive=true;if(prior?.pid){try{process.kill(prior.pid,0)}catch(e){alive=e.code!=='ESRCH'}}if(prior?.pid&&!alive){fs.unlinkSync(lock);fd=fs.openSync(lock,'wx')}else throw Error('Another API import is running or lock owner unknown; '+lock)}fs.writeFileSync(fd,JSON.stringify({pid:process.pid,startedAt:new Date().toISOString()}));let backup=null;try{if(isRemote){const combined=mergeRemotePackages(readJSON(REMOTE,{records:[]}),deepRedact(source));clean=deepRedact(combined.package);merge=combined.merge;}else clean=deepRedact(source);if(fs.existsSync(target)){backup=path.join(DIR,'recovery',path.basename(target)+'.'+Date.now()+'.json');atomic(backup,deepRedact(readJSON(target)));}atomic(target,clean);}finally{fs.closeSync(fd);fs.unlinkSync(lock)}
 return {imported:true,target,backup,source:input,merge,refresh:await refresh(),boundary:'Local import only. Records merge by platform+ID; failed/unverified/empty incoming packets preserve previous successful visible text. Pagination describes actual response pages, not entire account history.'}}
export async function main(argv=process.argv.slice(2)){const cmd=argv.shift()||'help',args={};for(let i=0;i<argv.length;i++){if(!argv[i].startsWith('--'))throw Error('Unknown positional argument');const k=argv[i].slice(2);if(!['offset','limit','platform','kind','project','query','id','chars','char-offset','input','branch'].includes(k))throw Error('Unknown option --'+k);if(!argv[i+1]||argv[i+1].startsWith('--'))throw Error('Value required --'+k);args[k]=argv[++i]}let result;if(cmd==='help')result=HELP;else if(cmd==='routing-status'){const active=readJSON(_publicDataPath("本地统一/对话记录/original-routing-state.json"),null);const legacy=readJSON(_publicDataPath("本地统一/对话记录/routing-state.json"),{decisions:{},recent:[]});const fsState=active||legacy;result={state:path.join(DIR,active?'original-routing-state.json':'routing-state.json'),mode:active?'original-semantic-binding-only':'withdrawn-legacy-state',updatedAt:fsState.updatedAt,decisions:Object.values(fsState.decisions).map(d=>({threadId:d.threadId,status:d.status,project:d.project,groupKey:d.groupKey,source:d.source,nativeMoveApplied:d.nativeMoveApplied===true,reason:d.reason})),boundary:fsState.boundary||'Legacy copy route withdrawn; this is historical state only',nativeMoves:active?Object.values(fsState.decisions).filter(d=>d.nativeMoveApplied).length:0};}else if(cmd==='recent'){result={updatedAtSource:'original native threads.updated_at',items:(await import('./auto-routing.mjs')).recentView()};}else if(cmd==='navigation')result=(await import('./management.mjs')).generateNavigation();else if(cmd==='resume')result=await (await import('./management.mjs')).resumeConversation(args.id,args,read);else if(cmd==='refresh')result=await refresh();else if(cmd==='import-api')result=await importAPI(args.input);else if(cmd==='list'){const x=load();result={...page(selected(x,args),args),refreshedAt:x.refreshedAt}}else if(cmd==='read')result=await read(args.id,args);else if(cmd==='search')result=await search(args.query,args);else if(cmd==='coverage'){const x=load();result={refreshedAt:x.refreshedAt,coverage:x.coverage,sources:x.sources,errors:x.errors,sqliteIssue:x.sqliteIssue,scope:x.scope}}else throw Error('Unknown command '+cmd);return result}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){main().then(result=>process.stdout.write(JSON.stringify(result,null,2)+'\n')).catch(e=>{process.stdout.write(JSON.stringify({error:redact(e.message)})+'\n');process.exitCode=1})}
